/**
 * Exercise Database - Ejercicios organizados por grupos musculares
 * Estructura: id, nombre, bodyPart, descripción, media (MP4), serie de recomendación
 * Diseñado para escalabilidad y fácil mantenimiento
 */

export type BodyPart = 'chest' | 'back' | 'shoulders' | 'trapezius' | 'biceps' | 'triceps' | 'forearm' | 'abs' | 'quadriceps' | 'hamstring' | 'calves';

export interface Exercise {
  id: string;
  name: string;
  bodyPart: BodyPart;
  description: string;
  execution: string[]; // Pasos de ejecución
  media: string; // Path a video MP4
  reps?: string;
  sets?: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

/**
 * Base de datos de ejercicios por grupo muscular
 * Los videos son placeholders - en producción usar URLs reales
 */
export const exerciseDatabase: Exercise[] = [
  // ===== PECHO (CHEST) =====
  {
    id: 'chest-001',
    name: 'Press de Banca Plano',
    bodyPart: 'chest',
    description: 'Press con barra o mancuernas en banco plano. Ejercicio fundamental para desarrollar pecho.',
    execution: [
      'Acuéstate en el banco con los pies firmemente en el suelo',
      'Agarra la barra con las manos separadas al ancho de los hombros',
      'Baja la barra hacia el pecho de forma controlada',
      'Presiona hacia arriba hasta extender completamente los brazos',
      'Mantén un ritmo constante sin rebotar la barra en el pecho',
    ],
    media: '',
    reps: '8-12',
    sets: 4,
    difficulty: 'intermediate',
  },
  {
    id: 'chest-002',
    name: 'Press Inclinado',
    bodyPart: 'chest',
    description: 'Press con mancuernas en banco inclinado. Enfoca en región superior del pecho.',
    execution: [
      'Ajusta el banco a 45 grados de inclinación',
      'Siéntate con la espalda firmemente apoyada',
      'Sostén las mancuernas a la altura de los hombros',
      'Presiona hacia arriba y al frente siguiendo un arco controlado',
      'Baja lentamente hasta sentir tensión en el pecho superior',
    ],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'chest-003',
    name: 'Press Declinado',
    bodyPart: 'chest',
    description: 'Press en banco con declive. Trabaja región inferior del pecho.',
    media: '',
    execution: [
      'Acuéstate en un banco declinado (15-30 grados)',
      'Los pies están arriba y la cabeza abajo',
      'Sostén la barra a la altura del pecho',
      'Presiona hacia arriba de forma controlada',
      'El movimiento enfatiza la parte baja del pecho',
    ],
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'chest-004',
    name: 'Fondos en Paralelas',
    bodyPart: 'chest',
    description: 'Fondos con inclinación hacia delante para enfoque en pecho.',
    execution: [
      'Sujétate de las barras paralelas con brazos extendidos',
      'Inclina el tronco hacia delante (importante para pecho)',
      'Dobla los codos bajando el cuerpo lentamente',
      'Baja hasta que los brazos formen ángulos de 90 grados',
      'Presiona hacia arriba volviendo a la posición inicial',
    ],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'advanced',
  },
  {
    id: 'chest-005',
    name: 'Aperturas con Mancuernas',
    bodyPart: 'chest',
    description: 'Movimiento de aislamiento para pectoral con mancuernas.',
    execution: [
      'Acuéstate en un banco plano con mancuernas en cada mano',
      'Brazos extendidos hacia arriba con ligera flexión de codos',
      'Abre los brazos en un movimiento de arco amplio',
      'Baja las mancuernas hasta sentir un estiramiento completo',
      'Vuelve a la posición inicial siguiendo el mismo arco',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'chest-006',
    name: 'Cruces en Polea',
    bodyPart: 'chest',
    description: 'Movimiento de aislamiento en polea alta para pecho inferior.',
    execution: [
      'De pie en el centro de una máquina de poleas',
      'Agarra las asas de las poleas altas con ambas manos',
      'Tira de las asas hacia el pecho en un movimiento de cruz',
      'Cruza los brazos frente a ti completamente',
      'Controla el retorno volviendo a la posición inicial',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'intermediate',
  },

  // ===== ESPALDA (BACK) =====
  {
    id: 'back-001',
    name: 'Dominadas',
    bodyPart: 'back',
    description: 'Ejercicio compuesto para espalda ancha y lats. Ligeramente más separadas que supinadas.',
    execution: [
      'Cuelgate de la barra con agarre pronado (palmas hacia afuera)',
      'Las manos deben estar separadas más que el ancho de los hombros',
      'Tira hacia arriba usando los músculos de la espalda',
      'Acerca tu barbilla o pecho a la barra',
      'Baja de forma controlada sin soltar completamente los brazos',
    ],
    media: '',
    reps: '6-12',
    sets: 4,
    difficulty: 'advanced',
  },
  {
    id: 'back-002',
    name: 'Jalón al Pecho',
    bodyPart: 'back',
    description: 'Jalón en polea alta. Alternativa excelente a dominadas.',
    execution: [
      'Siéntate en la máquina de jalón al pecho',
      'Agarra la barra con manos separadas al ancho de los hombros',
      'Tira la barra hacia tu pecho de forma controlada',
      'Contrae los músculos de la espalda en la parte inferior del movimiento',
      'Regresa lentamente a la posición inicial sin bloquear los brazos',
    ],
    media: '',
    reps: '10-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'back-003',
    name: 'Remo con Barra',
    bodyPart: 'back',
    description: 'Remo horizontal con barra. Compuesto para espalda media y baja.',
    execution: [
      'De pie con la barra a la altura de las caderas',
      'Dobla ligeramente las rodillas e inclina el tronco hacia delante',
      'Tira la barra hacia tu abdomen manteniendo la espalda recta',
      'Contrae fuerte los músculos de la espalda',
      'Baja la barra de forma controlada sin permitir que se golpee el suelo',
    ],
    media: '',
    reps: '8-12',
    sets: 4,
    difficulty: 'intermediate',
  },
  {
    id: 'back-004',
    name: 'Remo Sentado en Polea',
    bodyPart: 'back',
    description: 'Remo en máquina sentado. Aislamiento controlado para espalda.',
    execution: [
      'Siéntate en la máquina manteniendo la espalda recta',
      'Agarra el asa con ambas manos al nivel del pecho',
      'Tira hacia ti contrayendo los músculos de la espalda',
      'Lleva los codos por detrás del cuerpo',
      'Vuelve lentamente a la posición inicial',
    ],
    media: '',
    reps: '10-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'back-005',
    name: 'Remo Unilateral',
    bodyPart: 'back',
    description: 'Remo con mancuerna unilateral. Trabaja cada lado de forma independiente.',
    execution: [
      'Inclínate sobre un banco soportando un lado con la mano',
      'Sostén la mancuerna con el otro brazo colgando',
      'Tira la mancuerna hacia tu cadera posterior',
      'Mantén el codo pegado al cuerpo durante todo el movimiento',
      'Baja de forma controlada y repite con el otro lado',
    ],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'back-006',
    name: 'Pull-Over',
    bodyPart: 'back',
    description: 'Pull-over en polea o con mancuerna. Trabaja pecho y espalda.',
    execution: [
      'Acuéstate en un banco perpendicular con los pies en el suelo',
      'Sostén la mancuerna o la barra con ambas manos sobre el pecho',
      'Sin doblar mucho los codos, lleva el peso sobre y más allá de tu cabeza',
      'Siente el estiramiento completo en el pecho y espalda',
      'Devuelve el peso a la posición inicial con control',
    ],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'intermediate',
  },

  // ===== HOMBRO (SHOULDERS) =====
  {
    id: 'shoulders-001',
    name: 'Press Militar',
    bodyPart: 'shoulders',
    description: 'Press con barra de pie. Compuesto para deltoides anteriores.',
    execution: [
      'De pie con la barra a la altura del mentón',
      'Las manos separadas al ancho de los hombros',
      'Presiona la barra hacia arriba hasta extender completamente los brazos',
      'Mantén el core enganchado sin arquear demasiado la espalda',
      'Baja controladamente a la posición inicial',
    ],
    media: '',
    reps: '8-12',
    sets: 4,
    difficulty: 'intermediate',
  },
  {
    id: 'shoulders-002',
    name: 'Arnold Press',
    bodyPart: 'shoulders',
    description: 'Variación de press con mancuernas. Trabaja toda la región del deltoides.',
    execution: [
      'Siéntate con la espalda apoyada sosteniendo mancuernas a la altura de los hombros',
      'Palmas mirando hacia ti inicialmente',
      'Presiona hacia arriba mientras rota las palmas hacia afuera',
      'En la parte superior, las palmas están mirando hacia adelante',
      'Invierte el movimiento bajando con control',
    ],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'shoulders-003',
    name: 'Elevaciones Laterales',
    bodyPart: 'shoulders',
    description: 'Aislamiento para deltoides lateral. Da amplitud a hombros.',
    execution: [
      'De pie con una mancuerna en cada mano a los costados',
      'Brazos ligeramente doblados con ligera inclinación del cuerpo',
      'Levanta las mancuernas hacia los lados hasta la altura de los hombros',
      'El movimiento es controlado y pausado',
      'Baja lentamente a la posición inicial',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'shoulders-004',
    name: 'Elevaciones Frontales',
    bodyPart: 'shoulders',
    description: 'Aislamiento para deltoides frontal. Se puede hacer con mancuernas o barra.',
    execution: [
      'De pie con mancuernas en ambas manos o barra en frente',
      'Levanta los brazos hacia adelante hasta la altura del hombro',
      'Movimiento controlado hasta 90 grados',
      'Mantén los brazos rectos pero sin bloquear los codos',
      'Baja lentamente a la posición inicial',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'shoulders-005',
    name: 'Pájaros',
    bodyPart: 'shoulders',
    description: 'Pájaros o rear delt fly. Enfoca en deltoides posterior.',
    execution: [
      'Inclínate sobre un banco o máquina de deltoides posterior',
      'Sostén mancuernas ligeras con brazos ligeramente doblados',
      'Levanta las mancuernas hacia los lados formando un arco',
      'Contrae fuerte los músculos de la espalda posterior',
      'Baja con control a la posición inicial',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'shoulders-006',
    name: 'Face Pulls',
    bodyPart: 'shoulders',
    description: 'Jalón de cara con polea. Desarrolla deltoides posterior y mejora postura.',
    execution: [
      'De pie en frente de una polea alta con cuerda',
      'Tira la cuerda hacia tu rostro separando las manos',
      'Los codos finalizan por encima de los hombros',
      'Retrae los omóplatos atrás al final del movimiento',
      'Vuelve lentamente a la posición inicial',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },

  // ===== TRAPECIO (TRAPEZIUS) =====
  {
    id: 'trapezius-001',
    name: 'Encogimientos con Mancuernas',
    bodyPart: 'trapezius',
    description: 'Shrugs con mancuernas. Movimiento simple y efectivo para trapecios.',
    execution: [
      'De pie con mancuernas en ambas manos a los costados',
      'Contrae los hombros hacia arriba levantándolos lo máximo posible',
      'Mantén la contracción en la parte superior por 1-2 segundos',
      'Baja los hombros de forma controlada hasta la posición inicial',
      'No hagas movimientos de brazos, solo movimiento vertical de hombros',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'trapezius-002',
    name: 'Encogimientos con Barra',
    bodyPart: 'trapezius',
    description: 'Shrugs con barra. Permite usar más peso que con mancuernas.',
    execution: [
      'De pie sostén la barra con las manos separadas al ancho de los hombros',
      'Contrae y levanta los hombros hacia arriba',
      'Lleva los hombros lo más alto posible',
      'Mantén 1 segundo en la contracción máxima',
      'Baja controladamente sin soltar completamente la tensión',
    ],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'trapezius-003',
    name: 'Farmer Walks',
    bodyPart: 'trapezius',
    description: 'Caminar cargando peso. Desarrolla trapecios y agarre.',
    execution: [
      'De pie sostén mancuernas o kettlebells pesadas en ambas manos',
      'Mantén los hombros hacia atrás y el core enganchado',
      'Camina en línea recta manteniendo la postura erguida',
      'Controla la respiración mientras caminas',
      'Completa el número de pasos determinado manteniendo la tensión',
    ],
    media: '',
    reps: '30-40 pasos',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'trapezius-004',
    name: 'Remo al Cuello',
    bodyPart: 'trapezius',
    description: 'Remo vertical. Enfoca en trapecios superiores.',
    execution: [
      'De pie con la barra en frente a la altura de la cadera',
      'Las manos muy juntas separadas 10-15cm',
      'Tira la barra hacia arriba llevando los codos por encima de las muñecas',
      'Sube hasta la altura del mentón aproximadamente',
      'Baja de forma controlada sin perder la tensión',
    ],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'trapezius-005',
    name: 'Shrugs en Máquina',
    bodyPart: 'trapezius',
    description: 'Encogimientos en máquina especializada. Aislamiento controlado.',
    execution: [
      'Siéntate en la máquina de shrugs con espalda recta',
      'Agarra los mangos con las manos',
      'Levanta los hombros hacia arriba máximo',
      'Mantén un segundo en la contracción completa',
      'Baja lentamente controlando toda la amplitud del movimiento',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'trapezius-006',
    name: 'Face Pulls Trapezius',
    bodyPart: 'trapezius',
    description: 'Face pulls con enfoque en contracción de trapecios.',
    execution: [
      'De pie frente a una polea alta con cuerda',
      'Tira la cuerda hacia tu rostro separando las manos',
      'En la parte final, levanta los codos por encima de los hombros',
      'Retrae los omóplatos hacia atrás contrayendo fuerte',
      'Regresa lentamente a la posición inicial',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },

  // ===== BÍCEPS =====
  {
    id: 'biceps-001',
    name: 'Curl con Barra',
    bodyPart: 'biceps',
    description: 'Curl con barra recta. Clásico para bíceps.',
    execution: [
      'De pie con la barra al nivel de la cadera, palmas hacia adelante',
      'Brazos completamente extendidos pero sin bloquear los codos',
      'Dobla los codos levantando la barra hacia los hombros',
      'Movimiento controlado sin permitir que los hombros suban',
      'Baja la barra lentamente a la posición inicial manteniendo tensión',
    ],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'biceps-002',
    name: 'Curl Alterno',
    bodyPart: 'biceps',
    description: 'Curl alterno con mancuernas. Permite mayor rango de movimiento.',
    execution: [
      'De pie con mancuernas a los costados, palmas hacia dentro',
      'Levanta una mancuerna hacia el hombro mientras giras la palma hacia ti',
      'En la parte superior, la palma mira hacia el hombro',
      'Baja controladamente y repite con el otro brazo alternando',
      'Mantén un ritmo constante y controlado',
    ],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'biceps-003',
    name: 'Curl Martillo',
    bodyPart: 'biceps',
    description: 'Curl martillo con mancuernas. Trabaja bíceps y braquial.',
    execution: [
      'De pie con mancuernas a los lados, palmas enfrentadas',
      'Dobla los codos levantando las mancuernas hacia los hombros',
      'Las palmas permanecen mirándose entre sí todo el movimiento',
      'Siente la contracción en los bíceps y braquial',
      'Baja lentamente manteniendo la tensión',
    ],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'biceps-004',
    name: 'Curl en Polea',
    bodyPart: 'biceps',
    description: 'Curl en polea baja. Tensión constante en el movimiento.',
    execution: [
      'De pie frente a una polea baja con una cuerda o barra',
      'Agarra el implemento con palmas hacia delante',
      'Levanta los brazos hacia los hombros sin mover los codos',
      'Mantén la tensión en la parte superior del movimiento',
      'Baja de forma controlada sin permitir que los brazos se extiendan completamente',
    ],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'biceps-005',
    name: 'Curl Concentrado',
    bodyPart: 'biceps',
    description: 'Curl sentado concentrado. Máxima contracción y aislamiento.',
    execution: [
      'Siéntate con las piernas abiertas sosteniendo una mancuerna',
      'Apoya el codo del brazo de trabajo en el muslo interno',
      'Levanta la mancuerna concentrando todo en el bíceps',
      'Siente la máxima contracción en la parte superior',
      'Baja muy lentamente para maximizar el trabajo',
    ],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'biceps-006',
    name: 'Curl en Banco Inclinado',
    bodyPart: 'biceps',
    description: 'Curl en banco inclinado con mancuernas. Mayor estiramiento.',
    execution: [
      'Siéntate en un banco inclinado hacia atrás (45 grados)',
      'Sostén mancuernas a los lados brazos colgando',
      'Levanta las mancuernas hacia los hombros',
      'Mayor rango de movimiento y estiramiento que curls normales',
      'Baja controladamente para sentir el estiramiento completo',
    ],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'intermediate',
  },

  // ===== TRÍCEPS =====
  {
    id: 'triceps-001',
    name: 'Fondos en Paralelas',
    bodyPart: 'triceps',
    description: 'Fondos en paralelas con tronco vertical. Compuesto para tríceps.',
    execution: ['Sujétate de las barras paralelas con brazos extendidos', 'Dobla los codos bajando lentamente el cuerpo', 'Los codos permanecen pegados al cuerpo', 'Baja hasta formar ángulos de 90 grados en los codos', 'Presiona hacia arriba hasta la posición inicial'],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'triceps-002',
    name: 'Press Cerrado',
    bodyPart: 'triceps',
    description: 'Press de banca con agarre cerrado. Enfoca en tríceps.',
    execution: ['Acuéstate en un banco plano con la barra sobre el pecho', 'Manos separadas menos que el ancho de los hombros', 'Baja la barra llegando al pecho', 'Presiona hacia arriba concentrando en tríceps', 'Movimiento controlado sin permitir que los codos se abran'],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'triceps-003',
    name: 'Extensión en Polea',
    bodyPart: 'triceps',
    description: 'Extensión de tríceps en polea con cuerda.',
    execution: ['De pie frente a una polea alta con cuerda', 'Agarra la cuerda con palmas mirándose', 'Los codos permanecen firmes al lado del cuerpo', 'Estira los brazos hacia abajo hasta la extensión completa', 'Vuelve lentamente a la posición inicial'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'triceps-004',
    name: 'Extensión Por Encima',
    bodyPart: 'triceps',
    description: 'Extensión por encima de la cabeza con mancuerna. Máxima contracción.',
    execution: ['De pie o sentado sostén una mancuerna por encima de la cabeza', 'Brazo completamente extendido', 'Dobla el codo bajando la mancuerna detrás de la cabeza', 'Siente el estiramiento completo en el tríceps', 'Extiende nuevamente hacia arriba'],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'triceps-005',
    name: 'Skull Crushers',
    bodyPart: 'triceps',
    description: 'Rompecráneos acostado en banco. Aislamiento intenso.',
    execution: ['Acuéstate en un banco con una barra o mancuernas sobre el pecho', 'Brazos extendidos, codos sin bloquear', 'Dobla los codos bajando el peso hacia la cabeza', 'Las mancuernas descienden formando un arco hacia los lados', 'Extiende nuevamente manteniendo los codos en posición'],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'triceps-006',
    name: 'Patada de Tríceps',
    bodyPart: 'triceps',
    description: 'Patada unilateral con mancuerna. Máxima contracción.',
    execution: ['Apoya una rodilla en un banco', 'Sostén una mancuerna en la mano del lado de trabajo', 'Codo pegado al cuerpo a la altura de la cadera', 'Estira el brazo hacia atrás extendiendo completamente', 'Baja lentamente manteniendo control'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },

  // ===== ANTEBRAZO (FOREARM) =====
  {
    id: 'forearm-001',
    name: 'Curl de Muñeca',
    bodyPart: 'forearm',
    description: 'Curl de muñeca con palma hacia arriba. Trabaja flexores.',
    execution: ['Siéntate con las manos sosteniendo una barra sobre los muslos', 'Palmas mirando hacia arriba', 'Dobla las muñecas levantando el peso hacia arriba', 'Movimiento solo en la muñeca sin mover el antebrazo', 'Baja lentamente hasta estirar completamente'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'forearm-002',
    name: 'Curl Inverso',
    bodyPart: 'forearm',
    description: 'Curl inverso de muñeca. Trabaja extensores.',
    execution: ['Siéntate con las manos sosteniendo una barra sobre los muslos', 'Palmas mirando hacia abajo', 'Levanta el peso doblando las muñecas hacia arriba', 'Movimiento controlado solo en la muñeca', 'Baja armando para estirar los extensores'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'forearm-003',
    name: 'Farmer Walks',
    bodyPart: 'forearm',
    description: 'Caminar cargando peso. Desarrolla agarre y antebrazos.',
    execution: ['Sostén mancuernas o kettlebells pesadas en ambas manos', 'De pie con postura recta', 'Camina en línea recta sin soltar los objetos', 'Mantén la tensión en los antebrazos y agarre', 'Completa distancia determinada'],
    media: '',
    reps: '30-40 pasos',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'forearm-004',
    name: 'Dead Hangs',
    bodyPart: 'forearm',
    description: 'Colgarse de la barra. Entrena agarre y resistencia.',
    execution: ['Cuelgate de una barra con brazos extendidos', 'Brazos sobre los hombros separados', 'Mantén la posición colgando sin movimiento', 'Los antebrazos trabajan manteniendo el agarre', 'Aguanta el máximo tiempo posible'],
    media: '',
    reps: '20-30s',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'forearm-005',
    name: 'Curl Inverso Barra',
    bodyPart: 'forearm',
    description: 'Curl inverso con barra. Mayor peso y carga.',
    execution: ['De pie con una barra en las manos', 'Palmas mirando hacia abajo (pronado)', 'Dobla los codos levantando la barra', 'Movimiento controlado enfatizando extensores', 'Baja lentamente sin perder la tensión'],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'forearm-006',
    name: 'Pronación/Supinación',
    bodyPart: 'forearm',
    description: 'Rotaciones de muñeca con mancuerna. Trabaja rotadores.',
    execution: ['Sostén una mancuerna con un brazo extendido al frente', 'Empieza con la palma mirando hacia abajo', 'Rota la muñeca hacia arriba (supinación)', 'Luego rota hacia abajo (pronación)', 'Movimiento lento y controlado'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },

  // ===== ABDOMEN (ABS) =====
  {
    id: 'abs-001',
    name: 'Crunch',
    bodyPart: 'abs',
    description: 'Crunch clásico acostado. Trabaja recto abdominal superior.',
    execution: ['Acuéstate boca arriba con las rodillas dobladas', 'Manos detrás de la cabeza manteniendo el cuello relajado', 'Levanta los hombros del suelo contrayendo el abdomen', 'El movimiento viene del abdomen no del cuello', 'Baja lentamente manteniendo tensión'],
    media: '',
    reps: '15-20',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'abs-002',
    name: 'Elevación de Piernas',
    bodyPart: 'abs',
    description: 'Elevación de piernas colgado. Intenso para abdominales bajos.',
    execution: ['Cuelgate de una barra con brazos extendidos', 'Mantén el cuerpo recto sin impulso', 'Levanta las piernas hasta la altura horizontal', 'Movimiento controlado concentrando en abdominales bajos', 'Baja lentamente sin soltar la barra'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'abs-003',
    name: 'Plancha',
    bodyPart: 'abs',
    description: 'Isométrico para core. Posición fundamental para estabilidad.',
    execution: ['Posición de apoyo en antebrazos y punteras', 'Cuerpo forma línea recta de cabeza a talones', 'Core enganchado y contraído', 'Sin dejar cadera ni levantarla demasiado', 'Mantén la posición el tiempo especificado'],
    media: '',
    reps: '30-60s',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'abs-004',
    name: 'Ab Wheel',
    bodyPart: 'abs',
    description: 'Rueda abdominal. Movimiento muy intenso para abdominales.',
    execution: ['De rodillas sostén la rueda con ambas manos', 'Rueda hacia adelante extendiendo el cuerpo', 'El core mantiene la tensión durante toda la extensión', 'Rueda de vuelta hacia la posición inicial con control', 'Movimiento muy exigente'],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'advanced',
  },
  {
    id: 'abs-005',
    name: 'Crunch en Polea',
    bodyPart: 'abs',
    description: 'Crunch en máquina de polea. Resistencia progresiva.',
    execution: ['Arrodíllate en frente de una polea alta con cuerda', 'Agarra la cuerda detrás de la cabeza', 'Flexiona hacia abajo contrayendo abdominales', 'El movimiento es similar al crunch pero con resistencia', 'Vuelve a la posición inicial'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'abs-006',
    name: 'Russian Twists',
    bodyPart: 'abs',
    description: 'Rotaciones rusas. Trabaja oblicuos y core.',
    execution: ['Siéntate con las rodillas dobladas', 'Inclina el tronco hacia atrás formando ángulo de 45°', 'Levanta los pies del suelo si es posible', 'Rota el torso de un lado a otro', 'Puede sostener peso para mayor resistencia'],
    media: '',
    reps: '20 (10 c/lado)',
    sets: 3,
    difficulty: 'intermediate',
  },

  // ===== CUÁDRICEPS (QUADRICEPS) =====
  {
    id: 'quadriceps-001',
    name: 'Sentadilla Trasera',
    bodyPart: 'quadriceps',
    description: 'Sentadilla con barra en espalda. Compuesto fundamental.',
    execution: ['De pie con barra en la espalda, pies al ancho de los hombros', 'Baja bajando las caderas como si fueras a sentarte', 'Profundidad hasta que los muslos estén paralelos al suelo', 'Las rodillas siguen al línea de los pies', 'Sube presionando con piernas y glúteos'],
    media: '',
    reps: '8-12',
    sets: 4,
    difficulty: 'intermediate',
  },
  {
    id: 'quadriceps-002',
    name: 'Sentadilla Frontal',
    bodyPart: 'quadriceps',
    description: 'Sentadilla con barra en pecho. Enfatiza cuádriceps.',
    execution: ['De pie con barra en el pecho soportada por los hombros', 'Codos hacia adelante', 'Baja bajando las caderas en línea recta', 'Mayor énfasis en cuádriceps que en espalda baja', 'Sube presionando fuerte con las piernas'],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'quadriceps-003',
    name: 'Prensa de Piernas',
    bodyPart: 'quadriceps',
    description: 'Máquina de prensa. Segura y controlada para cuádriceps.',
    execution: ['Siéntate en la máquina con la espalda sioportada', 'Pies en la plataforma al ancho de los hombros', 'Baja bajando la plataforma doblando las rodillas', 'No dejes que las rodillas pasen más allá de los pies', 'Sube extendiendo completamente'],
    media: '',
    reps: '10-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'quadriceps-004',
    name: 'Zancadas',
    bodyPart: 'quadriceps',
    description: 'Lunges con mancuernas. Trabaja cuádriceps unilateralmente.',
    execution: ['De pie sosteniendo mancuernas a los lados', 'Da un paso hacia adelante grande', 'Baja el cuerpo doblando ambas rodillas', 'La rodilla trasera casi toca el suelo', 'Sube y regresa a posición inicial, repite con la otra pierna'],
    media: '',
    reps: '10-12 c/lado',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'quadriceps-005',
    name: 'Extensión de Piernas',
    bodyPart: 'quadriceps',
    description: 'Máquina de extensión. Aislamiento total para cuádriceps.',
    execution: ['Siéntate en la máquina con el rollo bajo encima del tobillo', 'Espalda contra el respaldo', 'Extiende las piernas hacia adelante contra la resistencia', 'Movimiento controlado sin bloquear las rodillas', 'Vuelve a la posición inicial'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'quadriceps-006',
    name: 'Step-ups',
    bodyPart: 'quadriceps',
    description: 'Subidas al banco. Trabaja cuádriceps con movimiento funcional.',
    execution: ['De pie frente a un banco', 'Sostén mancuernas si quieres mayor resistencia', 'Sube una pierna al banco', 'Sube el cuerpo hasta estar de pie en el banco', 'Baja lentamente', 'Alterna piernas'],
    media: '',
    reps: '10-12 c/lado',
    sets: 3,
    difficulty: 'intermediate',
  },

  // ===== ISQUIOTIBIALES (HAMSTRING) =====
  {
    id: 'hamstring-001',
    name: 'Peso Muerto Rumano',
    bodyPart: 'hamstring',
    description: 'PDR con barra. Compuesto para isquiotibiales y espalda baja.',
    execution: ['De pie con barra en frente a la altura de caderas', 'Pies al ancho de los hombros', 'Inclina el tronco hacia adelante bajando la barra', 'Las rodillas permanecen ligeramente dobladas', 'Siente el estiramiento en los isquiotibiales', 'Sube manteniendo la espalda recta'],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'hamstring-002',
    name: 'Curl Femoral Tumbado',
    bodyPart: 'hamstring',
    description: 'Curl femoral acostado. Aislamiento para isquiotibiales.',
    execution: ['Acuéstate boca abajo en la máquina', 'Las piernas extendidas', 'Dobla las rodillas levantando los talones hacia los glúteos', 'Contracción completa en la parte superior', 'Baja lentamente manteniendo tensión'],
    media: '',
    reps: '10-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'hamstring-003',
    name: 'Curl Femoral Sentado',
    bodyPart: 'hamstring',
    description: 'Curl femoral sentado en máquina. Variación de aislamiento.',
    execution: ['Siéntate en la máquina', 'Piernas extendidas bajo la barra', 'Dobla las rodillas jalando la barra hacia ti', 'Los muslos permanecen apoyados en el asiento', 'Contrae completamente en la parte inferior'],
    media: '',
    reps: '10-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'hamstring-004',
    name: 'Buenos Días',
    bodyPart: 'hamstring',
    description: 'Good mornings con barra. Compuesto para cadena posterior.',
    execution: ['De pie con barra en los hombros similarmente al squat', 'Pies separados al ancho de los hombros', 'Inclina el tronco hacia adelante desde la cadera', 'Mantén la espalda recta durante todo el movimiento', 'Sube volviendo a posición vertical'],
    media: '',
    reps: '8-12',
    sets: 3,
    difficulty: 'advanced',
  },
  {
    id: 'hamstring-005',
    name: 'Hip Thrust',
    bodyPart: 'hamstring',
    description: 'Puente de cadera o hip thrust. Explosion para glúteos e isquios.',
    execution: ['Apoya la espalda en un banco', 'Pies en el suelo, rodillas dobladas', 'Levanta las caderas hacia arriba contra resistencia', 'Contraer glúteos e isquiotibiales en la parte superior', 'Baja lentamente'],
    media: '',
    reps: '10-12',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'hamstring-006',
    name: 'Nordic Curl',
    bodyPart: 'hamstring',
    description: 'Curl nórdico. Intenso para flexores isquiotibiales.',
    execution: ['De rodillas con alguien sosteniendo los tobillos', 'Mantén el cuerpo recto como tabla', 'Inclínate hacia adelante lentamente', 'Los isquiotibiales trabajan para frenarte', 'Sube nuevamente si es posible'],
    media: '',
    reps: '5-8',
    sets: 3,
    difficulty: 'advanced',
  },

  // ===== GEMELOS (CALVES) =====
  {
    id: 'calves-001',
    name: 'Elevaciones de Pie',
    bodyPart: 'calves',
    description: 'Elevaciones de talones de pie. Clásico para gemelos.',
    execution: ['De pie con pies separados al ancho de los hombros', 'Manos apoyadas si necesitas balance', 'Levanta los talones del suelo hasta las puntas de los pies', 'Contraer los gemelos en la posición superior', 'Baja lentamente sin dejar que los talonees toquen completamente'],
    media: '',
    reps: '15-20',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'calves-002',
    name: 'Elevaciones Sentado',
    bodyPart: 'calves',
    description: 'Elevaciones de talones sentado. Enfatiza sóleo.',
    execution: ['Siéntate con los pies apoyados en el suelo', 'Las mancuernas o peso en los muslos si lo deseas', 'Levanta los talones enfatizando el sóleo', 'Los gemelos trabajan pero con énfasis diferente', 'Baja lentamente'],
    media: '',
    reps: '15-20',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'calves-003',
    name: 'Prensa de Gemelos',
    bodyPart: 'calves',
    description: 'Elevaciones en máquina de prensa de piernas.',
    execution: ['Siéntate en la máquina de prensa', 'Coloca solo las puntas de los pies en la plataforma', 'Los talones cuelgan fuera de la plataforma', 'Levanta empujando con los talones hacia arriba', 'Contrae y baja lentamente'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
  {
    id: 'calves-004',
    name: 'Elevación a Una Pierna',
    bodyPart: 'calves',
    description: 'Elevación unilateral de talón. Mayor intensidad.',
    execution: ['De pie sobre una pierna', 'La otra pierna doblada o levantada', 'Levanta el talón de la pierna de apoyo', 'Mayor resistencia que con ambas piernas', 'Mayor contracción de los gemelos'],
    media: '',
    reps: '10-12 c/lado',
    sets: 3,
    difficulty: 'intermediate',
  },
  {
    id: 'calves-005',
    name: 'Saltos Pliométricos',
    bodyPart: 'calves',
    description: 'Saltos para explosividad. Entrena poder en gemelos.',
    execution: ['De pie con pies separados al ancho de los hombros', 'Salta lo más alto posible usando los gemelos', 'Aterrizaje suave en las puntas de los pies', 'Inmediatamente salta nuevamente', 'Movimiento explosivo y rítmico'],
    media: '',
    reps: '10-15',
    sets: 3,
    difficulty: 'advanced',
  },
  {
    id: 'calves-006',
    name: 'Elevaciones en Hack',
    bodyPart: 'calves',
    description: 'Elevaciones en máquina hack squat. Aislamiento con peso.',
    execution: ['Entra en la máquina hack squat', 'De pie apoyado en la máquina', 'Coloca solo las puntasde los pies en la plataforma', 'Levanta los talones contrayendo gemelos', 'Movimiento controlado'],
    media: '',
    reps: '12-15',
    sets: 3,
    difficulty: 'beginner',
  },
];

/**
 * Obtiene ejercicios filtrados por grupo muscular
 */
export function getExercisesByBodyPart(bodyPart: BodyPart): Exercise[] {
  return exerciseDatabase.filter((exercise) => exercise.bodyPart === bodyPart);
}

/**
 * Obtiene todos los grupos musculares disponibles
 */
export function getAllBodyParts(): BodyPart[] {
  const parts = new Set<BodyPart>();
  exerciseDatabase.forEach((exercise) => {
    parts.add(exercise.bodyPart);
  });
  return Array.from(parts).sort();
}

/**
 * Metadatos de partes del cuerpo para UI
 */
export const bodyPartMetadata: Record<BodyPart, { label: string; icon: string; description: string }> = {
  chest: {
    label: 'Pecho',
    icon: '🏋️',
    description: 'Músculos pectorales',
  },
  back: {
    label: 'Espalda',
    icon: '💪',
    description: 'Lats, espalda ancha',
  },
  shoulders: {
    label: 'Hombros',
    icon: '⭐',
    description: 'Deltoides',
  },
  trapezius: {
    label: 'Trapecio',
    icon: '🏔️',
    description: 'Trapecios y cuello',
  },
  biceps: {
    label: 'Bíceps',
    icon: '💪',
    description: 'Músculos frontales del brazo',
  },
  triceps: {
    label: 'Tríceps',
    icon: '🎯',
    description: 'Músculos traseros del brazo',
  },
  forearm: {
    label: 'Antebrazo',
    icon: '🤜',
    description: 'Flexores y extensores',
  },
  abs: {
    label: 'Abdomen',
    icon: '⚡',
    description: 'Core y abdominales',
  },
  quadriceps: {
    label: 'Cuádriceps',
    icon: '🦵',
    description: 'Frente del muslo',
  },
  hamstring: {
    label: 'Isquiotibiales',
    icon: '🔥',
    description: 'Atrás del muslo',
  },
  calves: {
    label: 'Gemelos',
    icon: '👟',
    description: 'Pantorrillas',
  },
};
